name: Run unit tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install tools
      run: |
        sudo apt-get update
        sudo apt-get install cppcheck cmake
    - name: static analysis
      run: cppcheck --error-exitcode=1 src/
    - name: build
      run: |
        cmake -S . -B build
        cd build
        make
    - name: test
      run: make test
